JiscSD/rdss-archivematica-channel-adapter

.travis.yml, README.md, amclient/amclient.go, amclient/processing_config.go, amclient/transfer.go, amclient/transfer_session.go, amclient/transfer_session_test.go, broker/backend/kinesis/processor_test.go, consumer/consumer.go
This PR updates the adapter so the metadata of the dataset is also included in `metadata.json` - the entry has the value `objects/` in the `filename` column.
Also, this issue closes #23 and I've enabled coveralls.io and added some extra badges to the README file.
--- 
These will be the badges shown once this PR is merged:
[![Travis CI](https://travis-ci.org/JiscRDSS/rdss-archivematica-channel-adapter.svg?branch=master)](https://travis-ci.org/JiscRDSS/rdss-archivematica-channel-adapter) [![GoDoc](https://godoc.org/github.com/JiscRDSS/rdss-archivematica-channel-adapter?status.svg)](https://godoc.org/github.com/JiscRDSS/rdss-archivematica-channel-adapter) [![Coverage Status](https://coveralls.io/repos/github/JiscRDSS/rdss-archivematica-channel-adapter/badge.svg?branch=master)](https://coveral …
=> Problem: metadata of dataset is missing

amclient/transfer_session.go, amclient/transfer_session_test.go, broker/message/message.go, broker/message/message_metadata.go, broker/message/message_test.go, consumer/consumer.go, consumer/consumer_test.go
Related: #28.
This commit introduces a couple of changes:
- Create `metadata.csv` file instead of `metadata.json`. The latter was problematic.
- Update DataCite mapping.
rdss-canonical-data-model: https://github.com/JiscRDSS/rdss-canonical-data-model/commit/91a8600b5db958c50725d4a5727da601151f4eb6.
=> Ingest metadata updates

Dockerfile, Dockerfile.dev, Makefile
Added a new multi-stage `/Dockefile` that only uses 26.8MB. The old Dockerfile
can be found at `/Dockerfile.dev` (499MB) which is still the recommended option
if you are a developer.
=> Multi-stage Dockerfile

.travis.yml, Makefile, broker/backend/kinesis/processor_test.go
A data race (shared map) was blocking us from using `-race` before. I believe
this is because the mock of DynamoDB is not safe. This commit deletes this
test.
In the future, we should probably implement a similar test that runs against
dynalite as an integration test. That's exactly what kinsumer does, see:
https://github.com/twitchscience/kinsumer#testing.
=> Use test -race

consumer/consumer.go, consumer/consumer_unit_test.go
This closes #56.
I tried to write a test for it but `amclient` needs some refactoring: `TransferSession` should be an interface so I can have the `MetadataCreate` handler use a mock instead. Also the method that returns the struct isn't part of the `TransferService` interface but just coming straight from `amclient.Client`.
Solving the actual problem is a higher priority. I'll file an issue for the missing test.
=> Consumer: name files after fileName attr

Gopkg.lock, Gopkg.toml, Makefile, amclient/transfer_session.go, vendor/github.com/cenkalti/backoff/.gitignore, vendor/github.com/cenkalti/backoff/.travis.yml, vendor/github.com/cenkalti/backoff/LICENSE, vendor/github.com/cenkalti/backoff/README.md, vendor/github.com/cenkalti/backoff/backoff.go, vendor/github.com/cenkalti/backoff/backoff_test.go, vendor/github.com/cenkalti/backoff/context.go, vendor/github.com/cenkalti/backoff/context_test.go, vendor/github.com/cenkalti/backoff/example_test.go, vendor/github.com/cenkalti/backoff/exponential.go, vendor/github.com/cenkalti/backoff/exponential_test.go, vendor/github.com/cenkalti/backoff/retry.go, vendor/github.com/cenkalti/backoff/retry_test.go, vendor/github.com/cenkalti/backoff/ticker.go, vendor/github.com/cenkalti/backoff/ticker_test.go, vendor/github.com/cenkalti/backoff/tries.go, vendor/github.com/cenkalti/backoff/tries_test.go
Introduce retry with exponential back-off in amclient's TransferSession.Start().
Typically I wouldn't vendor a new package for a simple retry but we wanted to use an exponential back-off algorithm and that became much harder so I ended up using [github.com/cenkalti/backoff](https://github.com/cenkalti/backoff) which gives us a stable and configurable implementation that we can also use in other situations, e.g. http/s3 downloads, etc...
=> amclient: add backoff to TransferSession.Start()

Makefile, cmd/version.go, hack/gofmtcheck.sh
I've realized that we're not checking fmt errors. This commit makes the needed
changes so this happens when we run `make` which is also used by Travis CI.
The user can also run the following commands manually:
- `make gofmt` to fix fmt errors
- `make gofmtcheck` to detect fmt errors (via exit codes)
This closes #65.
---
@philgray-ark: this should be merged before #63 because that PR brings some formatting issues. #63 will need to be rebased.
=> Add gofmt support

Dockerfile.multi-stage
We don't currently use the multi-stage Docker build but it's still there for when we can use it (AWS still running old version of Docker). I tested it for other reasons and I realized that it was missing the git tool which is required during the build.
This commit updates the file so git is installed at the build stage.
It's low priority.
=> Problem: Dockerfile.multi-stage doesn't install git

broker/message/headers.go, broker/message/message.go, broker/message/message_metadata.go, broker/message/message_test.go, broker/message/schema_intelectual_asset.go, broker/message/schema_material_asset.go, broker/message/schema_research_object.go, broker/message/uuid.go, broker/message/uuid_test.go, broker/repository.go, broker/repository_test.go, consumer/consumer_test.go, fixtures/messages/body/metadata/create/request.json, fixtures/messages/body/metadata/delete/request.json, fixtures/messages/body/metadata/read/request.json, fixtures/messages/body/metadata/read/response.json, fixtures/messages/body/metadata/update/request.json, fixtures/messages/example.json, fixtures/messages/header/example.json
[RDSSARK-371](https://jiscdev.atlassian.net/browse/RDSSARK-371).
Add custom `UUID` type used for JSON encoding/decoding. Use it in the fields where the message API specifies that the type is UUID, e.g.: `messageId` or in a variety or fields in the message payloads.
=> broker/message: enforce use of UUIDs

broker/message/headers.go, broker/message/message_test.go
This reverts a change introduced in #70 that shouldn't have been introduced in the first place.
It closes #73.
=> broker/message: treat MessageHistory as array

README.md, broker/broker.go, broker/config.go, broker/message/validation.go, broker/message/validation_test.go, cmd/consumer/consumer.go, cmd/root.go
This commit adds a new setting that allows user to switch off validation:
RDSS_ARCHIVEMATICA_ADAPTER_BROKER.VALIDATION=true
Also, added some benchmarks to compare the impact that the validator may have
in the message processor. You can run the benchmarks with the following command:
$ go test -bench=Validation ./broker/message -benchtime=1s
Below you can see the results seen in my laptop. Depending on the size of the
messages the results will be different, e.g. `VeryComplex` uses a JSON blob
of 7kb but still manages to validate 10k messages within a second.
```
BenchmarkValidationNoOp-4               30000000                41.3 ns/op
BenchmarkValidationSimple-4               500000              2045 ns/op
BenchmarkValidationComplex-4              200000              8959 ns/op …
```
=> broker/message: validation toggle

.travis.yml
Travis translates `1.x` into the latest minor version available.
Effectively this means that we would be using Go 1.10 (released four days ago), but it also means that we don't have to keep updating `.travis.yml` when new versions of Go are released.
Also, added `tip` to test against new versions in development.
Allow it to fail.
=> Travis: use Go 1.x and tip

Gopkg.lock, Gopkg.toml, README.md, broker/broker.go, broker/config.go, broker/config_test.go, broker/message/message.go, broker/message/validation.go, cmd/consumer/consumer.go
This is in addition to #80 (see also #77). It extends the possible uses of the environment string `RDSS_ARCHIVEMATICA_ADAPTER_BROKER.VALIDATION`. These are the options:
- When set to `true`, the adapter will reject invalid messages and the validation issues will be logged with `DEBUG` level.
- When set to warnings, the adapter will not reject invalid messages but the validation issues will be logged with `DEBUG` level.
- When set to `false`, message validation will not be performed.
`true` remains as the default value.
=> Add validation modes

README.md, amclient/transfer_session.go, amclient/transfer_session_test.go, cmd/consumer/consumer.go, cmd/root.go, consumer/consumer.go
https://jiscdev.atlassian.net/browse/RDSSARK-336
This pull request makes changes to the `MetadataCreate` message handler to abort the transfer when the download process fails.
For this to be possible, `amclient.TransferSession` now stages the transfer in the `tmp` directory of the Archivematica Shared Directory before it's moved into the `standardTransfer` watched directory.
The environment string:
```
RDSS_ARCHIVEMATICA_ADAPTER_CONSUMER.ARCHIVEMATICA_TRANSFER_DEPOSIT_DIR=/var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer
```
... is replaced by:
```
RDSS_ARCHIVEMATICA_ADAPTER_CONSUMER.ARCHIVEMATICA_SHARED_DIR=/var/archivematica/sharedDirectory
```
This won't affect you if you have been relying on the default which is true for existing deployments of the …
=> Abort transfers when downloads fail

hack/minikine/package.json
[kinesalite v1.11.7](https://github.com/mhart/kinesalite/releases/tag/v1.11.7) has been released today and it includes a fix for a problem we experienced with messages being delivered more than once. We had to use a fork but that's not necessary anymore once we install the update.
=> minikine: use kinesalite v1.11.7

amclient/transfer_session.go, amclient/transfer_session_test.go, broker/message/message_metadata.go, broker/message/message_vocabulary.go, consumer/consumer.go, consumer/consumer_unit_test.go, consumer/storage.go, consumer/storage_test.go
Related links:
- https://jiscdev.atlassian.net/browse/RDSSARK-491
- https://jiscdev.atlassian.net/wiki/spaces/RDSSAR/pages/429064213/Metadata+Update+Messages
Limitations:
- Re-ingest doesn't happen yet, we're just starting a new transfer.
- The only implementation at the moment of the `Storage` interface puts the data in memory (basically a hash of ObjectUUID » TransferUUID). I will ~update the PR soon~ **submit a new PR** with an implementation for DynamoDB.
```
time="2018-03-26T02:06:06Z" level=info msg="Message received" cmd=consumer count=3 type=MetadataUpdate version=UNKNOWN
time="2018-03-26T02:06:06Z" level=debug msg="Reingesting transfer." TODO="Implement real reingest." cmd=consumer handler=MetadataUpdate message=efac164a-c9bd-45e0-8991-2c505e400300 …
```
=> Add handler for MetadataUpdate message

README.md, cmd/consumer/consumer.go, cmd/root.go, consumer/consumer.go, consumer/consumer_test.go, consumer/consumer_unit_test.go, consumer/storage.go, consumer/storage_test.go, hack/minikine/dynalite.js
#91 added the `consumer.Storage` interface with a simple builtin in-memory implementation. This PR completes that work by adding support for DynamoDB.
Related: https://jiscdev.atlassian.net/browse/RDSSARK-491.
=> consumer: add DynamoDB storage backend

broker/message/validation.go
Tentative fix, needs further investigation.
Also, added `validate` command - useful if you want to validate a message but you don't have the whole stack running:
go run main.go validate -f /home/foobar/message.json
=> Handle panic in email validation

hack/minikine/minikine.js
We used to expect and use a "main" stream but this has now been split into "input" and "output" streams, inkeeping with how RDSS is now deployed ([config here](https://github.com/JiscRDSS/rdss-institutional-ecs-clusters/blob/develop/infra-archivematica/tf/kinesis.tf)). 
This pull request updates the minikine config so that the expected streams are available, even in mock.
The Channel Adapter code itself is unchanged: the consumer should treat "input" as its main queue, whilst the producer should treat "output" as its main queue.
=> minikine: use input and ouput streams instead of main

README.md, amclient/amclient.go, amclient/amclient_test.go, amclient/transfer_session.go, amclient/transfer_session_test.go, amclient/v2_package.go, amclient/v2_package_test.go, cmd/consumer/consumer.go, cmd/root.go, consumer/consumer.go, consumer/consumer_test.go
So far we only had implemented form-encoded requests (used in the v1 namespace of Dashboard API).
This is just the internal abstraction to interface with any endpoint made available under `/api/v2beta/package`.
---
`amclient.TransferSession` is an abstraction that simplifies the creation of a transfer. It's used by our `MetadataCreate` handler whenever we're ready to start a transfer. Roughly, it used to do the following:
1. Create a temporary directory in the Archivematica Shared Directory.
2. Download and include a processing configuration.
3. Incorporate files to the transfer (`objects/`).
4. Incorporate checksums and metadata in the transfer directory.
5. Move the transfer to the watched directory.
6. Approve the transfer (with retry/backoff).
The new process is:
1. Create a temporary …
=> Support async start transfer

.travis.yml, README.md, hack/coverage.sh
Replace `coverage.sh` with a simpler script that ignores pb files effectively
and takes advantage of Go's most recent ability to hide vendor directories.
This brings the coverage report up to ~80% again.
This closes #96.
=> Fix coverage report

adapter/handlers.go, amclient/amclient.go, amclient/transfer.go, amclient/transfer_session.go, amclient/transfer_session_test.go, amclient/transfer_test.go, amclient/v2_jobs.go, amclient/v2_jobs_test.go, amclient/v2_package.go, amclient/v2_package_test.go, amclient/v2_task.go, amclient/v2_task_test.go, amclient/wait.go, amclient/wait_test.go
- [1/4] [Upgrade to RDSS MAS v4.0.0](https://github.com/JiscRDSS/rdss-archivematica-channel-adapter/pull/110)
- [2/4] [Add SQS/SNS backend](https://github.com/JiscRDSS/rdss-archivematica-channel-adapter/pull/111)
- **[3/4] Publish PreservationEvent message**
- [4/4] [Support multitenancy](https://github.com/JiscRDSS/rdss-archivematica-channel-adapter/pull/113)
---
The message is published only when the AIP is stored hence this PR brings changes to the `amclient` package to allow users wait until such action completes.
=> [3/4] Publish PreservationEvent message

README.md, app/app.go, app/cmd_server.go, app/config.go, broker/broker.go, go.mod, go.sum, integration/scripts/example_run.sh
It is not clear whether in practice the Error Message Queue or Invalid Message
Queue are going to be utilised as described in the specification.
This PR updates the broker package so messages are not published into the
topics but logged instead, when their ARNs have been set to empty string.
The two relevant config attributes are:
- `adapter.queue_send_error_addr`
- `adapter.queue_send_invalid_addr`
These are examples of logged events for both the invalid and error queues:
time="2019-07-25T13:51:15-07:00" level=warning msg="[GENERR001]: invalid character 'i' looking for beginning of value" cmd=server error-queue="invalid[disabled]"
time="2019-07-25T13:51:21-07:00" level=warning msg="[GENERR006]: 1: unknown tenantJiscID" cmd=server error-queue="error[disabled]"
The logger learns a new …
=> Add no-op invalid/error queues

broker/message/timestamp.go, broker/message/timestamp_test.go
@howard-jisc, here's a small change to accommodate the `2019-10-31T16:20:05.921+0000` format seen in your latest message.
=> message: support new date-time format
